// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuZiR-nH6315z5ZWmXABUrgpVvUCg9Itg',
    appId: '1:249268348860:web:61b7bfe909911d6e822db9',
    messagingSenderId: '249268348860',
    projectId: 'safenest-41fcc',
    authDomain: 'safenest-41fcc.firebaseapp.com',
    storageBucket: 'safenest-41fcc.firebasestorage.app',
    measurementId: 'G-7JB2EKZKD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTTzHB69nw8zDJY9BA6DIjuLTqfsZSblo',
    appId: '1:249268348860:android:b60f321a97416246822db9',
    messagingSenderId: '249268348860',
    projectId: 'safenest-41fcc',
    storageBucket: 'safenest-41fcc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuZiR-nH6315z5ZWmXABUrgpVvUCg9Itg',
    appId: '1:249268348860:web:9a90cee844bec673822db9',
    messagingSenderId: '249268348860',
    projectId: 'safenest-41fcc',
    authDomain: 'safenest-41fcc.firebaseapp.com',
    storageBucket: 'safenest-41fcc.firebasestorage.app',
    measurementId: 'G-QNKNTPR0VK',
  );
}
